# Generated by Django 5.1.3 on 2024-12-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualWeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('avg_max_temp', models.FloatField(blank=True, null=True)),
                ('avg_min_temp', models.FloatField(blank=True, null=True)),
                ('total_precipitation', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_stats', to='station.weatherstation')),
            ],
            options={
                'ordering': ['station', 'year'],
                'unique_together': {('station', 'year')},
            },
        ),
    ]
